# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  deploy-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
     name: dev
     url: 'https://covid19-pmpa.vercel.app/'
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, DEVVVVV!
      # Runs a set of commands using the runners shell
      
  deploy-prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
     name: prod
     url: 'https://covid19-pmpa.vercel.app/r'
    needs: deploy-dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, PROD!
      # Runs a set of commands using the runners shell
     
